{% set name = "blink" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/jart/blink/releases/download/{{ version }}/blink-{{ version }}.tar.gz
    sha256: 09ffc3cdb57449111510bbf2f552b3923d82a983ef032ee819c07f5da924c3a6
    patches:
      - patches/0001-b31fed832b10d32eadaec885fb20dacbb0eb6986.patch

build:
  skip: true  # [win]
  number: 0
  script: ./configure --prefix="$PREFIX" --enable-vfs && make -j && make install

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - sysroot_linux-64 2.17  # [linux64]

test:
  commands:
    - blink -h

about:
  home: https://github.com/jart/blink
  summary: Tiniest x86-64-linux emulator
  description: |
    Blink is a virtual machine that runs x86-64-linux programs on different
    operating systems and hardware architectures.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
